#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

build-config-file /etc/greetd/config.toml.d /etc/greetd/config.toml
build-config-file /etc/greetd/wlgreet.toml.d /etc/greetd/wlgreet.toml
