#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -e

/usr/sbin/wlgreet >/dev/null 2>/dev/null
labwc --exit >/dev/null 2>/dev/null
