#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

leaprun signal-wayland-session-started
exec systemd-cat --identifier=lxqt startlxqtwayland
